In [1]:

from bs4 import BeautifulSoup
import requests
import numpy as np
import pandas as pd
from geopy.geocoders import Nominatim
import folium

In [2]:
url = 'https://en.wikipedia.org/wiki/List_of_neighbourhoods_in_Toronto'
result = requests.get(url)

In [3]:
df = pd.DataFrame(columns=['Hood', 'Latitude', 'Longitude'])
df.head()

Empty DataFrame
Columns: [Hood, Latitude, Longitude]
Index: []

In [4]:
soup = BeautifulSoup(result.content, 'html.parser')
table = soup.find('table')
lis = table.find_all('li')

list_of_n = []
for li in lis:
    a = li.find('a')
    list_of_n.append(a.get('title').split(", ")[0].split(" (neighbourhood)")[0].split(" (Toronto)")[0] )

In [5]:
df['Hood'] = pd.Series(list_of_n)
print(df.shape)
df.head()

(32, 3)

              Hood Latitude Longitude
0   Alexandra Park      NaN       NaN
1        The Annex      NaN       NaN
2  Baldwin Village      NaN       NaN
3      Cabbagetown      NaN       NaN
4        CityPlace      NaN       NaN

In [6]:
df.drop_duplicates(inplace=True)
print(df.shape)
df.head()

(32, 3)

              Hood Latitude Longitude
0   Alexandra Park      NaN       NaN
1        The Annex      NaN       NaN
2  Baldwin Village      NaN       NaN
3      Cabbagetown      NaN       NaN
4        CityPlace      NaN       NaN

In [7]:
to_drop_unknown = []
geolocator = Nominatim(user_agent="coursera")
for index, row in df.iterrows():
    address = row['Hood'] + ', Toronto'
    try:
        location = geolocator.geocode(address)
        latitude = location.latitude
        longitude = location.longitude
        print('The geograpical coordinate of {} are {}, {}.'.format(address, latitude, longitude))
        df.loc[index, 'Latitude'] = latitude
        df.loc[index, 'Longitude'] = longitude
    except AttributeError:
        print('Cannot do: {}, will drop index: {}'.format(address, index))
        to_drop_unknown.append(index)

df.head()

The geograpical coordinate of Alexandra Park, Toronto are 43.65075755, -79.40430754323067.
The geograpical coordinate of The Annex, Toronto are 43.6703377, -79.407117.
The geograpical coordinate of Baldwin Village, Toronto are 43.6776885, -79.4081645.
The geograpical coordinate of Cabbagetown, Toronto are 43.6644734, -79.3669861.
The geograpical coordinate of CityPlace, Toronto are 43.6392482, -79.3963865.
The geograpical coordinate of Chinatown, Toronto are 43.6529237, -79.3980316.
The geograpical coordinate of Church and Wellesley, Toronto are 43.6655242, -79.3838011.
The geograpical coordinate of Corktown, Toronto are 43.6573699, -79.3565129.
The geograpical coordinate of Discovery District, Toronto are 43.6575555, -79.3894803.
The geograpical coordinate of Distillery District, Toronto are 43.6502947, -79.3595401.
The geograpical coordinate of Toronto Entertainment District, Toronto are 43.64383755, -79.38669247414063.
Cannot do: East Bayfront, Toronto, will drop index: 11
The geograpical coordinate of Fashion District, Toronto are 43.6454561, -79.3949942.
The geograpical coordinate of Financial District, Toronto are 43.64866395, -79.38153972121495.
The geograpical coordinate of Garden District, Toronto are 43.6564995, -79.3771141.
The geograpical coordinate of Grange Park, Toronto are 43.652196599999996, -79.39231921757992.
The geograpical coordinate of Harbord Village, Toronto are 43.6615225, -79.4097446.
The geograpical coordinate of Harbourfront, Toronto are 43.6400801, -79.3801495.
The geograpical coordinate of Kensington Market, Toronto are 43.6552136, -79.4022604.
Cannot do: Little Japan, Toronto, will drop index: 19
The geograpical coordinate of Moss Park, Toronto are 43.6546438, -79.3697278.
The geograpical coordinate of Old Town, Toronto are 43.6708625, -79.37279241253721.
The geograpical coordinate of Quayside, Toronto are 43.6472502, -79.35817207837727.
The geograpical coordinate of Queen Street West, Toronto are 43.6524006, -79.3793646.
The geograpical coordinate of Regent Park, Toronto are 43.6607056, -79.3604569.
The geograpical coordinate of South Core, Toronto are 43.6421064, -79.3774455.
The geograpical coordinate of St. James Town, Toronto are 43.6694032, -79.3727041.
The geograpical coordinate of St. Lawrence, Toronto are 43.649422, -79.3714278.
The geograpical coordinate of Toronto Islands, Toronto are 43.6230544, -79.39431563721035.
The geograpical coordinate of Trefann Court, Toronto are 43.6564893, -79.3628297.
The geograpical coordinate of University of Toronto, Toronto are 43.663461999999996, -79.39775965337452.
The geograpical coordinate of Yorkville, Toronto are 43.6713861, -79.3901677.

              Hood Latitude Longitude
0   Alexandra Park  43.6508  -79.4043
1        The Annex  43.6703  -79.4071
2  Baldwin Village  43.6777  -79.4082
3      Cabbagetown  43.6645   -79.367
4        CityPlace  43.6392  -79.3964